version: "3.8"
services:
  api:
    container_name: api_c
    build: ./api
    # image: panosfan/api
    ports:
      - "4000:4000"
  client:
    container_name: client_c
    build: ./client
    # image: panosfan/client
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
